### ISSUE TITLE
Senior profile for longitudinal tracking

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#613]
As an outcomes researcher, I want to store information related to longitudinal tracking so that we can get meaningful reporting of outcomes.

In order to perform longitudinal tracking on students, a detailed profile must be maintained for each student to allow for follow-up and reporting of outcomes.  Attached is an example form.  The Network application needs to track all the information on this form for each member.  Some of the information is already tracked and some will need to be added.

[Senior Profile Template.docx](https://github.com/edbirmingham/network/files/1981150/Senior.Profile.Template.docx)

Profile items to be added.
- [ ] Member picture. [Image]
- [x] High school GPA [Number]
- [x] ACT Score [Number]
- [x] Cell phone number [Text]
- [x] Relative cell phone number [Text]
- [x] Relative email address [Text]
- [x] Facebook name [Text]
- [x] Twitter handle [Text]
- [x] Instagram handle [Text]
- [x] Sex (Male, Female) [Single select list]
- [x] Race (Black or African American, White, Asian, American Indian or Alaska Native, Native Hawaiian or Pacific Islander) [Single select list]
- [x] Are you Hispanic/Latino? (Yes, No) [Single select list]

Graduation survey.
- [ ] Intended Career. [Text]
- [ ] Next year's plans.  (College, Job, Military, Other) [Multiple select list]
- [ ] College/Employer/Military Branch [Text]
- [ ] Intended Major/Job [Text]
- [ ] Predicted Starting Salary [Number]
- [ ] Predicted debt [Number]
- [ ] Ed Experiences (Skills Building, Executive Internship, College Visits, Site Visits, Student Change Makers, Network Nights) [Multiple select list]
- [ ] Skills [Text]
- [ ] Awards or Certifications Earned [Text]
- [ ] Other organizations worked with and significant accomplishments [Text]
- [ ] What you gained from your academy [Text]
- [ ] Thoughts about Birmingham Education Foundation (Ed) [Text]

**Comment by anthonycrumley** [comment]
@cecelacey All the profile fields, other than the photo, have been added and have been released to the site.  Also, the new member, show member, and edit member pages have been reorganized.  Please review and let me know if that organization of information makes sense to you.
